FROM node:16-alpine as development

ENV NODE_ENV=development

WORKDIR /usr/src/client/user

COPY package*.json ./
RUN npm install
COPY . .

# RUN npm run build
CMD ["sh", "-c", "npm start"]

EXPOSE 4000
