version: "3.9"
services:
  cache:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning --requirepass Bo02l119204.
    volumes:
      - cache:/data/cache
  api:
    container_name: jumbobids_api
    restart: unless-stopped
    image: jumbobids_api_prod:1.0.0
    environment:
      - NODE_ENV="production"
    env_file:
      - ./.env
    build:
      context: stem
      target: production
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    networks:
      - shared-network

  client.admin:
    container_name: jumbobids_admin
    restart: unless-stopped
    image: jumbobids_admin_prod:1.0.0
    build:
#      target: production
      context: client/admin
      dockerfile: Dockerfile
    ports:
      - "7000:7000"
    networks:
      - shared-network
    depends_on:
      - api

  client.user:
    container_name: jumbobids_user
    restart: unless-stopped
    image: jumbobids_user_prod:1.0.0
    build:
      context: client/user
      target: production
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - shared-network
    depends_on:
      - api

networks:
  shared-network:
volumes:
  cache:
    driver: local