name: Deploy client user

on:
  push:
    branches:
      - client.user
  pull_request:
    branches:
      - client.user

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Netlify Deployment
    steps:
      - name: Get the source code
        uses: actions/checkout@v2
        with:
          ref: client.user
      - name: "install Node"
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: install project dependencies
        run: npm install

      - name: Build
        run: npm run build
        env:
          CI: false
          REACT_APP_TYPESENSE_API_KEY: ${{ secrets.TYPESENSE_SEARCH_ONLY_KEY }}
          REACT_APP_TYPESENSE_CLOUD_HOST: ${{ secrets.TYPESENSE_CLOUD_HOST }}
          REACT_APP_TYPESENSE_CLOUD_PORT: ${{ secrets.TYPESENSE_CLOUD_PORT }}
          REACT_APP_TYPESENSE_CLOUD_PROTOCOL: "https"

      - name: Deploy to netlify
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_ACCESS_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_API_ID }}
        with:
          args: deploy --dir=build --prod
          secrets: '["NETLIFY_ACCESS_TOKEN", "NETLIFY_SITE_API_ID"]'
