name: Distribute code to branches

on:
  push:
    branches:
      - main

jobs:
  distribute:
    runs-on: ubuntu-latest
    name: "Distribute code"
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - name: "Split code to branches"
        env:
          GH_ACESS_TKN: ${{ secrets.GH_ACESS_TKN }}
        run: |
          git clone https://user:$GH_ACESS_TKN@github.com/hane-smitter/jumbo_bids_docker jumbobids

          mkdir jumbo_bids
          pwd
          cd jumbobids
          pwd
          git checkout -B stem
          echo $(pwd)
          ls -al
          cp -r ./.git ../jumbo_bids
          cp -r ./stem ../jumbo_bids
          cd ../jumbo_bids
          find ./stem ! -name "." ! -name ".." -type f,d -exec mv -t . '{}' '+'
          rmdir stem

          git add -A
          git commit -m "Stem branch update $GITHUB_JOB"

          git remote -v

          git push --set-upstream origin stem
