name: Distribute code to branches

on:
  push:
    branches:
      - main

env:
  GH_ACESS_TKN: ${{ secrets.GH_ACESS_TKN }}
  USERNAME: "hane-smitter"
  USER_EMAIL: "hanesmitter3@gmail.com"

jobs:
  apisourcecode:
    runs-on: ubuntu-latest
    name: "Get API source code"
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - name: "Split code to stem branch"
        run: |
          git clone -b main https://user:$GH_ACESS_TKN@github.com/hane-smitter/jumbo_bids_docker jumbobids

          mkdir jumbo_bids_tmp
          echo "jumbobids si uko"
          ls
          cd jumbobids

          git config --global user.name $USERNAME
          git config --global user.email $USER_EMAIL
          git remote set-url origin https://$USERNAME:$GH_ACESS_TKN@github.com/hane-smitter/jumbo_bids_docker.git

          # stem source code
          git checkout --orphan stem
          cp -rf ./stem ../jumbo_bids_tmp/
          rm -rf *
          cp -rf ../jumbo_bids_tmp/stem/* .
          git add -A
          git commit -m "Stem branch update $GITHUB_RUN_ID"

          git push --set-upstream origin stem -f
  clientusersourcecode:
    needs: apisourcecode
    runs-on: ubuntu-latest
    name: "Get client.user source code"
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - name: "Split code to client.user branch"
        run: |
          git clone -b main https://user:$GH_ACESS_TKN@github.com/hane-smitter/jumbo_bids_docker jumbobids

          mkdir jumbo_bids_tmp
          cd jumbobids

          git config --global user.name $USERNAME
          git config --global user.email $USER_EMAIL
          git remote set-url origin https://$USERNAME:$GH_ACESS_TKN@github.com/hane-smitter/jumbo_bids_docker.git

          # client.user source code
          git checkout main
          git checkout --orphan client.user
          cp -rf ./client/user ../jumbo_bids_tmp/
          rm -rf *
          cp -rf ../jumbo_bids_tmp/user/* .
          git add -A
          git commit -m "Client.user branch update $GITHUB_RUN_ID"

          git push --set-upstream origin client.user -f
  clientadminsourcecode:
    needs: apisourcecode
    runs-on: ubuntu-latest
    name: "Get client.admin source code"
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - name: "Split code to client.admin branch"
        run: |
          git clone -b main https://user:$GH_ACESS_TKN@github.com/hane-smitter/jumbo_bids_docker jumbobids

          mkdir jumbo_bids_tmp
          cd jumbobids

          git config --global user.name $USERNAME
          git config --global user.email $USER_EMAIL
          git remote set-url origin https://$USERNAME:$GH_ACESS_TKN@github.com/hane-smitter/jumbo_bids_docker.git

          # client.admin source code
          git checkout main
          git checkout --orphan client.admin
          cp -rf ./client/admin ../jumbo_bids_tmp/
          rm -rf *
          cp -rf ../jumbo_bids_tmp/admin/* .
          git add -A
          git commit -m "Client.admin branch update $GITHUB_RUN_ID"

          git push --set-upstream origin client.admin -f
